baseURL = 'https://ajency.github.io/cibil-dashboard/'
languageCode = 'en-us'
title = 'Cibil Dashboard'
theme = 'dashboard'
publishDir =  'docs'

[markup.goldmark.parser.attribute]
block = true
title = true